"""Add profile fields to Personne model

Revision ID: d2a5f7b8e9c0
Revises: c171641ae0d8
Create Date: 2025-06-17 02:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a5f7b8e9c0'
down_revision = 'c171641ae0d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personne', sa.Column('email', sa.String(length=150), nullable=True))
    op.add_column('personne', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('personne', sa.Column('profile_picture', sa.String(length=200), nullable=True))
    op.add_column('personne', sa.Column('notification_preferences', sa.Boolean(), nullable=True, server_default='1'))
    op.create_unique_constraint('uq_personne_email', 'personne', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_personne_email', 'personne', type_='unique')
    op.drop_column('personne', 'notification_preferences')
    op.drop_column('personne', 'profile_picture')
    op.drop_column('personne', 'bio')
    op.drop_column('personne', 'email')
    # ### end Alembic commands ###